/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package calcequity;

import java.text.DecimalFormat;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import sitEquity.EquityServer;

/**
 *
 * @author Michael
 */
public class SitPanel extends javax.swing.JPanel {

    /**
     * Creates new form SitPanel
     */
    public SitPanel(String title) {
        initComponents();
        innBG = new ButtonGroup();
        innBG.add(innTopButton);
        innBG.add(innBottomButton);
        sitTitle.setText(title);
        innTopButton.setSelected(true);
        setVisible(true);
        
    }
    
    public int getSit() {
        int res = 0;
        res = 6*(new Integer(inning.getText())-1);
        if (innBottomButton.isSelected())
            res+=3;
        if (out1Button.isSelected()){
            res++;
            if (out2Button.isSelected())
                res++;
        }
        res = res*100 +50;
        int rDiff = new Integer(homScore.getText())- new Integer(visScore.getText());
        if (innTopButton.isSelected())
            res -= rDiff;
        else
            res += rDiff;
        res = res*10;
        
        if (base1Button.isSelected())
            res++;
        if (base2Button.isSelected())
            res+=2;
        if (base3Button.isSelected())
            res+=4;
        
        return res;
        
    }
    // displays situation given situation and home score
    public void setSit(int sit, int hs) {   
        homScore.setText(new Integer(hs).toString());
        int outs = sit / 1000;
        Integer inn = new Integer((outs /6)+1);
        inning.setText(inn.toString());
        int tb = outs % 6;
        int scoreBase = sit % 1000;
        int scoreDiff = scoreBase / 10;
        int vs=0;  //visitor score
        if (tb<3) {
            innTopButton.setSelected(true);
            vs = hs + (scoreDiff - 50);
        }
        else {
            innBottomButton.setSelected(true);
            vs = hs -(scoreDiff - 50);
        }
        visScore.setText(new Integer(vs).toString());
        int rn = sit % 10;
        if (rn % 2 == 1 )  //1b occupied
             base1Button.setSelected(true);
        else
             base1Button.setSelected(false);
        if (rn==2 || rn==3 || rn==6 || rn==7)  //2b occupied
             base2Button.setSelected(true);
        else
             base2Button.setSelected(false); 
        
        if (rn> 3)  //3b occupied
             base3Button.setSelected(true);
        else
             base3Button.setSelected(false);
        
        int out  = outs % 3;
        if (out > 0)
            out1Button.setSelected(true);
        else
            out1Button.setSelected(false);
         if (out > 1)
            out2Button.setSelected(true);
        else
            out2Button.setSelected(false);
        
        String eq = String.format("%.2f", EquityServer.getScore(sit)*100);
        equity.setText(eq);
        
        setVisible(true);
        
    }
    public void setEquity() {
        //System.out.println("sit "+getSit()+"    equity "+  EquityServer.getScore(getSit()));
        double eqt = EquityServer.getScore(getSit()) *100;
        String eq = String.format("%.2f",eqt);
          
         // System.out.println("sit "+getSit()+"    equity "+  EquityServer.getScore(getSit())+"  format "+eq); 
        equity.setText(eq);
    }
    public void setEnabled(boolean b) {
       base1Button.setEnabled(b);
        base2Button.setEnabled(b);
        base3Button.setEnabled(b);
        innTopButton.setEnabled(b);
        innBottomButton.setEnabled(b);
        out1Button.setEnabled(b);
        out2Button.setEnabled(b);
        inning.setEnabled(b);
        visScore.setEnabled(b);
        homScore.setEnabled(b);
        equity.setEnabled(false);
        
       
       
    }
    public int getHomeScore() { return new Integer(homScore.getText()); }
    public boolean isTopofInning() {return innTopButton.isSelected();  }
    public JRadioButton getOut1() {return out1Button; }
    public JRadioButton getOut2() {return out2Button; }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base1Button = new javax.swing.JRadioButton();
        base3Button = new javax.swing.JRadioButton();
        base2Button = new javax.swing.JRadioButton();
        visLabel = new javax.swing.JLabel();
        homLabel = new javax.swing.JLabel();
        out1Button = new javax.swing.JRadioButton();
        out2Button = new javax.swing.JRadioButton();
        equity = new javax.swing.JTextField();
        visScore = new javax.swing.JTextField();
        homScore = new javax.swing.JTextField();
        innLab = new javax.swing.JLabel();
        innTopButton = new javax.swing.JRadioButton();
        innBottomButton = new javax.swing.JRadioButton();
        inning = new javax.swing.JTextField();
        eqLabel = new javax.swing.JLabel();
        sitTitle = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setMaximumSize(new java.awt.Dimension(189, 228));
        setMinimumSize(new java.awt.Dimension(189, 228));
        setPreferredSize(new java.awt.Dimension(198, 228));

        base1Button.setText("1B");
        base1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                base1ButtonActionPerformed(evt);
            }
        });

        base3Button.setText("3B");

        base2Button.setText("2B");

        visLabel.setText("VIS");

        homLabel.setText("HOM");

        out1Button.setText("Outs");

        equity.setDisabledTextColor(new java.awt.Color(0, 102, 51));
        equity.setMargin(new java.awt.Insets(2, 2, 5, 2));

        visScore.setText("0");
        visScore.setDisabledTextColor(new java.awt.Color(0, 102, 51));

        homScore.setText("0");
        homScore.setDisabledTextColor(new java.awt.Color(0, 102, 51));

        innLab.setText("INN");

        innTopButton.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        innTopButton.setText("Top");

        innBottomButton.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        innBottomButton.setText("Bottom");

        inning.setText("1");
        inning.setDisabledTextColor(new java.awt.Color(0, 102, 51));

        eqLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        eqLabel.setText("Home Team Win %");

        sitTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sitTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sitTitle.setText("Initial Situation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(sitTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(innLab, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inning, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(innTopButton)
                    .addComponent(innBottomButton))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(visLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(homLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visScore, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homScore, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(base2Button))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(base3Button)
                .addGap(53, 53, 53)
                .addComponent(base1Button))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(out1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(out2Button)))
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(eqLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(equity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sitTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(innLab, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(inning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(innTopButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(innBottomButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(visLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(homLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(visScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(homScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(base2Button)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(base3Button)
                    .addComponent(base1Button))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(out1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(out2Button))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eqLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void base1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_base1ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_base1ButtonActionPerformed
private ButtonGroup innBG;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton base1Button;
    private javax.swing.JRadioButton base2Button;
    private javax.swing.JRadioButton base3Button;
    private javax.swing.JLabel eqLabel;
    private javax.swing.JTextField equity;
    private javax.swing.JLabel homLabel;
    private javax.swing.JTextField homScore;
    private javax.swing.JRadioButton innBottomButton;
    private javax.swing.JLabel innLab;
    private javax.swing.JRadioButton innTopButton;
    private javax.swing.JTextField inning;
    private javax.swing.JRadioButton out1Button;
    private javax.swing.JRadioButton out2Button;
    private javax.swing.JLabel sitTitle;
    private javax.swing.JLabel visLabel;
    private javax.swing.JTextField visScore;
    // End of variables declaration//GEN-END:variables
}
